### ISSUE TITLE
Undefined function money_format [PHP 7.4]

### ISSUE THREAD

**Issue by JeroenBoesten** [lukepolo/laracart#223] opened 2017-12-12 22:03 UTC
**Hello,**

I really like the package, but while developing on Windows I came accross the folowing error: undefined function money_format. This turned out to be a function that is not supported on windows and is used in LaraCart.php on line 697, commenting out this line made it work again.

I would love to see a fix in the future to work around this function if this is possible. Attached the screenshot from the error.

![image](https://user-images.githubusercontent.com/5631345/33910866-879b1096-df90-11e7-92a1-6e07f4f31cb1.png)

**Greetings,**

**Comment by lukepolo** [comment] 2017-12-13 00:49
@Jeroendedoem 

Right?! There is a couple of solutions but none that I like. I started in 2.0 to rewrite most of LaraCart. And in that I have made a new formatter that you can customize rather than deciding for the user what they should use. 

With that in mind, I don't currently have a solution besides moving to linux. Im more than happy to accept PR's !

Maybe something that can replace it if those functions don't exist?

**Comment by Jeroendedoem** [comment] 2017-12-15 15:36
@lukepolo 
After some searching I came accross this post:
[http://php.net/manual/en/function.money-format.php#89060](url)
By adding that function to the Laracart.php it seems that the problem is solved. I ran some basic tests but didn't ran into any problems. Perhaps you could add this function and test a bit more before releasing.

**Comment by it-can** [comment] 2019-12-02 12:41
@lukepolo seems that php7.4 is deprecating the money_format function... https://www.php.net/manual/en/migration74.deprecated.php

**Comment by lukepolo** [comment] 2019-12-02 14:18
Oh fun, guess its time to re-write this package 👍

**Comment by lukepolo** [comment] 2019-12-02 14:48
Looks like we can just use https://www.php.net/manual/en/class.numberformatter.php for 5.3 and up. Which should solve this for windows as well.

**Comment by it-can** [comment] 2019-12-02 17:00
yeah would also change the composer.json file to require the intl extension...

```
"ext-intl" : "*"
```

**Comment by lukepolo** [comment] 2020-05-01 15:25
@it-can @JeroenBoesten 

I started on a new version but needs testing. Is this something that you can assist in?

**Comment by lukepolo** [comment] 2020-05-01 15:33
https://github.com/lukepolo/laracart/releases/tag/1.10.0

**Closed by lukepolo** 2020-05-01 15:33 UTC
Labels: bug, help wanted, high-priority

**Comment by smccoy78** [comment] 2020-05-12 19:27
@lukepolo I can assist in testing or whatever else you need. Just hit me up.
